config/routes.rb
TBMS::Application.routes.draw do

 
  match '/status/:id' => 'log_messages#handle_url', :as => "status"
  match '/status' => 'log_messages#handle_header', :as => 'plain_status'
  match '/log/handle/:id' => 'log_messages#handle_url'

  match "profile/:id" => "emailaccounts#zip_of_id",  :as => :zip_by_id,
        :constraints => { :id => /\d+/ }
  match "profile/:id/ok" => "emailaccounts#was_successfully_updated",
        :constraints => { :id => /\d+/ }
  match "profile/:email" => "emailaccounts#zip_of_email",:as => :generate_id,
        :constraints => { :email => /.*@.*/ }

  match "/groups/:id/edit/set_params" => "groups#set_params"
  match "/user.current/upload" => "users#upload"

  match '/subaccounts/:id/delete' => 'emailaccounts#delete_subaccount', :as => :delete_subaccount
  match 'groups/:id/propagate' => 'groups#overwrite_member_configs', :as => :override_members

  resources :emailaccounts
  resources :log_messages, :path => "/log"

  match "emailaccounts/:id/edit/set_params" => "emailaccounts#set_params"
  match "emailaccounts/:id/edit/information" => "emailaccounts#change_information"
  match 'emailaccounts/:id/groupsettings' => "emailaccounts#group_configuration", :as => :reset_account
  resources :groups
  
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  resources :users
  resource :user, :as => 'account'
  resources :user_sessions

  root :to => "emailaccounts#index"
end

app/models/group.rb
# Emailaccounts can belong to groups and merge their preferences
# with the groups. This merge is done once on the creation
# of the account and then on request.
# Author:: Aaron Karper <akarper@students.unibe.ch>
include GroupsHelper
class Group < ActiveRecord::Base
  # This is somewhat suboptimal, but inheritance in databases and
  # rails is really hard work.

	validates_presence_of :name
  validates_uniqueness_of :name
	has_many :emailaccounts
	belongs_to :group
	has_many :groups
	serialize :preferences

	def initialize params={}
		super params
		self.preferences = Hash.new
  end

  # Every User belongs to a group, which might be the default_group
  def self.default_group
    @default_group ||=
        Group.find_by_name("No Group") ||
            Group.create(:name => "No Group",
                         :preferences => {
                             :html => "true",
                             :signature => "This is just a template signature"})
    @default_group
  end

	# a list of all members (groups and emailaccounts)
	def members
		self.groups + self.emailaccounts
	end

	def to_s
		self.name
	end

	# the preferences in the hierarchy down to this point.
	def final_preferences
		if not self.group.nil?
			merge_down
		else
			self.preferences
		end
	end

	# Overwrite the supergroups preferences if necessary
	def merge_down
		self.group.final_preferences.merge self.preferences
	end

  # Changes are propagated down the hierarchy.
  def propagate_update
    self.preferences = self.group.final_preferences unless self.group.nil?
    self.members.each {|member| member.propagate_update}
  end

  # Change the preferences according to the FileCreator.
  def set_params params
	  raise "No Params" if params.nil?
	  params.each do |key, value|
	    raise "key nil" if key.nil?
	    raise "value nil" if value.nil?
	     self.preferences[key.to_sym] = value if FileCreator::valid_key?(key.to_sym)
	  end
    raise "Couldn't save" unless self.save
  end

end

app/controllers/groups_controller.rb
# Groups are a collection of emailaccounts that belong and are
# handled together. They have preferences and can overwrite
# the preferences of the users.
# This controller can only be used when logged in as admin.
class GroupsController < ApplicationController
  #Throws a ActionController::InvalidAuthenticityToken exception when requests token doesn't match the current secret token.
  protect_from_forgery :secret => @secret_key

  #Catch and render ActionController::InvalidAuthenticityToken exception
  rescue_from ActionController::InvalidAuthenticityToken, :with => :forgery_error
  def
    forgery_error(exception); render :text => exception.message;
  end

  # Restricts access for every method in this controller to logged in user only.
  before_filter :require_user
  before_filter :group_by_id, :only => [:show, :edit, :set_params, :update,
                                        :destroy, :overwrite_member_configs]

  # helper that provides a group for the commands.
  def group_by_id
    @profile = Group.find(params[:id])
    raise "No Group found" if @profile.nil?
  end

  # GET /groups
  # GET /groups.xml
  def index
    @profiles = Group.all

    respond_to do |format|
      format.html # index.html.haml
      format.xml  { render :xml => @profiles }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    respond_to do |format|
      format.html # show.html.haml
      format.xml  { render :xml => @profile }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @profile = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.xml
  def create
    @profile = Group.new(params[:group])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    respond_to do |format|
      if @profile.update_attributes(params[:group])
        format.html { redirect_to(@profile, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
      respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end

  def set_params
    @group = Group.find(params[:id])
    raise "No Group found" if @group.nil?
    @group.set_params(params)
    redirect_to group_path, :notice => 'Settings for this group were successfully saved.'
  end

  # Overwrite the users configuration with the own preferences.
  def overwrite_member_configs
    @profile.propagate_update
    redirect_to group_path, :notice => 'Settings propagated for all members'
  end
end

app/views/groups/_form.html.haml
%notice
  = flash[:notice]
%br
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2
        = pluralize(@profile.errors.count, "error")
        prohibited this account from being saved:
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li
            = msg
  
  %fieldset
    %legend Create Group
    %table
      %tr
        %td
          = f.label :name
        %td
          = f.text_field :name
      %tr
        %td  
          = submit_tag("Create")

app/views/groups/edit.html.haml
%h1 Editing group

%notice
  = flash[:notice]
%br
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2
        = pluralize(@profile.errors.count, "error")
        prohibited this account from being saved:
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li
            = msg
  
  %fieldset
    %legend Edit Group
    %table
      %tr
        %td
          = f.label :name
        %td
          = f.text_field :name
      %tr
        %td
          = submit_tag("Save")

= link_to 'Back', groups_path

app/views/groups/index.html.haml
%notice
  = flash[:notice]
- if flash[:error]
  %error
    =flash[:error]
  
  %br
  %br
%h2 Group List
%br
%br
= link_to 'New Group', new_group_path
%hr
%br
%table.users
  %tr
    %th Name
    %th Members
    %th
    %th 
  - @profiles.each do |group|
    %tr
      %td= link_to  group.name, group
      %td= group.members.size
      %td= link_to 'Edit Name', edit_group_path(group)
      - if group.name != "No Group"
        %td= link_to 'Delete', group, :confirm => "Are you sure you want to delete \"#{group.name}\"?", :method => :delete
      -else 
        %td

app/views/groups/new.html.haml
%h1 New group

= render 'form' 
%br
= link_to 'Back', groups_path 

app/views/groups/show.html.haml
%notice
  = flash[:notice]
  %br
= javascript_include_tag 'jquery-1.5.2.min.js'
%br
%h2= Group
%br
%br
= link_to "Set all Members back", override_members_path(@profile), :confirm => "Do you really want to reset all the members settings?"
|
= link_to 'Edit Name', edit_group_path(@profile)
|
= link_to 'Back', groups_path
%hr
%br
%table
  %tr
    %td
      %b Name:
    %td
      = @profile.name
  %tr
    %td
      %b Group:
    %td= @profile.group.to_s
  %tr
%br
%a#showMem(href="#")Show all Members

%table.users#show
  %tr
    %th Name
    %th Email
    %th
  - @profile.groups.each do |group|
    %tr
      %td= group.name
      %td
      %td= link_to 'Show', group
      %td= link_to 'Delete', group, :confirm => "Do you really want to delete #{group.name}?", :method => :delete
  - @profile.emailaccounts.each do |email|
    %tr{:class => email.outdated? ?  "outdated" : "uptodate" }
      %td= link_to email.name, email
      %td= link_to email.name, email
      %td
        = link_to 'Delete', email, :confirm => "Do you really want to delete #{email.name}?", :method => :delete

%br
%br
= render "shared/preferences"
%br
= link_to 'Back', groups_path

:javascript

  $("#show").hide();
  var show = true;
  $("#showMem").click(function () {
        if(show){ 
          $("#show").show();
          show = false;
        }
        else {
           $("#show").hide();
           show = true;
        }
        return true;
      });