config/routes.rb
TBMS::Application.routes.draw do

 
  match '/status/:id' => 'log_messages#handle_url', :as => "status"
  match '/status' => 'log_messages#handle_header', :as => 'plain_status'
  match '/log/handle/:id' => 'log_messages#handle_url'

  match "profile/:id" => "emailaccounts#zip_of_id",  :as => :zip_by_id,
        :constraints => { :id => /\d+/ }
  match "profile/:id/ok" => "emailaccounts#was_successfully_updated",
        :constraints => { :id => /\d+/ }
  match "profile/:email" => "emailaccounts#zip_of_email",:as => :generate_id,
        :constraints => { :email => /.*@.*/ }

  match "/groups/:id/edit/set_params" => "groups#set_params"
  match "/user.current/upload" => "users#upload"

  match '/subaccounts/:id/delete' => 'emailaccounts#delete_subaccount', :as => :delete_subaccount
  match 'groups/:id/propagate' => 'groups#overwrite_member_configs', :as => :override_members

  resources :emailaccounts
  resources :log_messages, :path => "/log"

  match "emailaccounts/:id/edit/set_params" => "emailaccounts#set_params"
  match "emailaccounts/:id/edit/information" => "emailaccounts#change_information"
  match 'emailaccounts/:id/groupsettings' => "emailaccounts#group_configuration", :as => :reset_account
  resources :groups
  
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  resources :users
  resource :user, :as => 'account'
  resources :user_sessions

  root :to => "emailaccounts#index"
end

app/models/emailaccount.rb
include EmailaccountHelper
include TemplateHelper
# Emailaccounts store their configuration (in the <code>preferences</code>
# map) and provide users with the corresponding zip files. It starts without
# a group, but it can be provided later, if need be. It has serveral
# profile ids, that represent the different clients with the same configuration.
#
# Author: 
class Emailaccount < ActiveRecord::Base

  validates_presence_of :email
  validates_presence_of :name
  validates_format_of :email,
                      :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  # We identify an account by its email on the first request.
  validates_uniqueness_of :email

  serialize :preferences
  serialize :informations
  belongs_to :group
  has_many :profile_ids,
           :autosave => true,
           :dependent => :destroy,
           :conditions => {:emailaccount_type => "listed"}
  has_one :standard_subaccount,
          :class_name => "ProfileId",
          :autosave => true,
          :dependent => :destroy,
           :conditions => {:emailaccount_type => "standard"}
  validate :not_too_many_ids

  after_initialize :setup_members

  def not_too_many_ids
    if too_many_ids
      errors.add_to_base ("Too many profile ids")
    end
  end

  def too_many_ids
     ProfileId.count(:conditions => {:emailaccount_id => self.id, :emailaccount_type => 'listed'}) >= max_id_count
  end

  def max_id_count
    10
  end

  def setup_members
    self.group ||= Group.default_group    # Idiomatic way to set if it has not been set yet.
    self.preferences ||= self.group.final_preferences
    self.informations ||= {:email => email, :name => name}
    self.create_standard_subaccount
  end

  # makes a new profile id to track the up-to-date-ness of another client.
  def generate_profile_id
    if not too_many_ids
      self.profile_ids.create :emailaccount_type => 'listed'
    end
  end

  def set_group param
    return nil if param.nil?
    group = Group.find(param)
    self.group = group || Group.default_group
  end

  # Sets the configuration of the emailaccount
  def set_params params
    raise "No Params" if params.nil?
    params.each do |key, value|
      raise "key nil" if key.nil?
      raise "value nil" if value.nil?
      self.preferences[key.to_sym] = value if valid_key?(key)
    end
    raise "save failed: #{errors}" unless self.save
    assure_created_zip
  end

  # Checks if the provided key can be handled by the FileCreator
  def valid_key? key
    key and (FileCreator::valid_key?(key.to_sym))
  end

  # Ensures that the zip file is up to date.
  def assure_created_zip
    FileCreator::createNewZip(self)
    raise "No file created" unless File.exists? zip_path
  end

  # ensures that the zip file exists and gives the path to it
  def assure_zip_path
    assure_created_zip
    zip_path
  end

  def zip_path
    FileCreator::completeZipPath self
  end


  # the preferences merged with the group's
  def final_preferences
    if not self.group.nil?
      merge_down
    else
      self.preferences
    end
  end

  # Overwrite the supergroups preferences if necessary
  def merge_down
    self.group.final_preferences.merge self.preferences
  end

  # Part of the Composite Pattern that can update the whole dependency tree if necessary.
  def propagate_update
    self.preferences = self.group.preferences if self.group
    raise "Couldn't save" unless self.save
    assure_created_zip
  end

 def outdated?
   outdated = self.profile_ids.any? { |p| p.outdated? }
   raise "Couldn't save" unless self.save
   outdated
 end

  # gives the fully instanciated template of the signature (@see EmailaccountHelper)
  def signature
    template = preferences[:signature] or ""
    dict = TemplateHelper::make_dict self.informations
    sig = TemplateHelper::instanciate_template template, dict
  end
end

app/controllers/emailaccounts_controller.rb
# Handles the interaction with the emailaccounts.
# This includes
#     * CRUD
#     * Providing the zips
#     * Handing out identifying ids
#     * Management of the user's configuration
# All actions except for getting the zip require the admin to be logged in.
class EmailaccountsController < ApplicationController
	#Throws a ActionController::InvalidAuthenticityToken exception when requests token doesn't match the current secret token.
  protect_from_forgery :secret => @secret_key

  #Catch and render ActionController::InvalidAuthenticityToken exception
  rescue_from ActionController::InvalidAuthenticityToken, :with => :forgery_error
  def
    forgery_error(exception); render :text => exception.message;
  end
  
  before_filter :require_user, :except => [ :zip_of_id, :zip_of_email ]
  before_filter :emailaccount_by_id, :only => [:show, :update,
                                               :destroy,
                                               :set_params, :group_configuration,
                                                :change_information]


  # helper that provides all methods with an emailaccount
  def emailaccount_by_id
    @profile = Emailaccount.find(params[:id])
    raise "No such Emailaccount #{id}!" if @profile.nil?
  end
  # Paginates and shows the emailaccounts.
  # GET /emailaccounts
  # GET /emailaccounts.xml
  def index
    @search = Emailaccount.search(params[:search])
    @profiles = @search.page(params[:page]).per(20)
    errors = @profiles.select { |e| e.standard_subaccount.nil? }
    if not errors.empty?
      raise errors.inject("") {|e,f| e + "\nno standard profileid for email #{f.email}"}
    end
    respond_to do |format|
      format.html # index.html.haml
      format.xml  { render :xml => @profiles }
    end
  end

  def not_modified
  end

  # Shows a single emailaccount
  # GET /emailaccounts/1
  # GET /emailaccounts/1.xml
  def show
    respond_to do |format|
      format.html # show.html.haml
      format.xml  { render :xml => @profile }
    end
  end

  # Shows the interface for new Emailaccounts
  # GET /emailaccounts/new
  # GET /emailaccounts/new.xml
  def new
    @profile = Emailaccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # POST /emailaccounts
  # POST /emailaccounts.xml
  def create
    @profile = Emailaccount.new(params[:emailaccount])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Emailaccount was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /emailaccounts/1
  # PUT /emailaccounts/1.xml
  def update
    respond_to do |format|
      if @profile.update_attributes(params[:emailaccount])
        format.html { redirect_to(@profile, :notice => 'Emailaccount was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "show" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /emailaccounts/1
  # DELETE /emailaccounts/1.xml
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(emailaccounts_url) }
      format.xml  { head :ok }
    end
  end

  def set_params
    @profile.set_group params[:group]
    @profile.set_params(params)
    redirect_to emailaccount_path, :notice => "Settings for this account were successfully saved."
  end

  # Get the configuration zip and a header with a brand new id.
  def zip_of_email
    @profile = Emailaccount.find_by_email(params[:email])
    response.headers["X-TBMS-Profile-ID"] = @profile.generate_profile_id.to_s
    zip_path = @profile.assure_zip_path
	  send_file zip_path
  end

  # Get the configuration zip.
  def zip_of_id
    cacheTime = Time.rfc2822(request.env["HTTP_IF_MODIFIED_SINCE"]) rescue nil
    if request.headers['X-TBMS-Status'] == "false"
      redirect_to status_path(params[:id])
    end
    emailaccount = ProfileId.find(params[:id]).emailaccount

    if not modified(emailaccount)
      render :nothing => true, :status => 304
    else
      response.headers['Last-Modified'] = emailaccount.updated_at.httpdate
      zip_path = emailaccount.assure_zip_path
      send_file zip_path
    end
  end

    def modified(emailaccount)
      return true unless request.headers.include? 'If-Modified-Since'
      since_date = Time.parse request.headers['If-Modified-Since']

      last_modification = emailaccount.updated_at
      return true if last_modification.nil?

      since_date < last_modification
    end

  # tells the server, that the configuration was successfully received.
  def was_successfully_updated
    subaccount = ProfileId.find(params[:id])
    subaccount.downloaded
  end

  # Propagates the groups configuration to this account.
  def group_configuration
    @profile.propagate_update
    redirect_to emailaccount_path, :notice => "Reset Account settings to groups"
  end

  # What it says on the tin
  def delete_subaccount
    subaccount = ProfileId.find(params[:id])
    raise "No such subaccount" if subaccount.nil?
    emailaccount = subaccount.emailaccount
    subaccount.destroy
    respond_to do |format|
      format.html { redirect_to(emailaccount_path(emailaccount), :notice => "Deleted ProfileId") }
      format.xml  { head :ok }
    end
  end

  def change_information
    keys = params\
                    .select {|key,val| /key_\d+/.match(key) and val.present?}\
                    .collect {|key,val| [(/key_\d+/.match(key))[1].to_i, val.to_sym]}\
                    .sort_by {|key,val| key}\
                    .collect {|key,val| val}
    values = params\
                    .select {|key,val| /value_\d+/.match(key) and val.present?}\
                    .collect {|key,val| [(/value_\d+/.match(key))[1].to_i, val]}\
                    .sort_by {|key,val| key}\
                    .collect {|key,val| val}
    key_values = keys.zip(values).to_hash
    @profile.informations= key_values
    raise "Couldn't save profile #{@profile.email}:\n* #{@profile.errors[:base].join '\n* '}" unless @profile.save
    redirect_to emailaccount_path, :notice => "Settings for this account were successfully saved."
  end

end

app/views/emailaccounts/edit.html.haml
%table
  %tr
    %td
      %b Email:
    %td
      = @emailaccount.email
  %tr
    %td
      %b Name:
    %td
      = @emailaccount.name
  %tr
%br
%hr
%br 
= form_tag(:action => "setParams") do
  %fieldset
    %legend Send all Mails in HTML
    %table
      %tr
        %td
          = label_tag("ON")
        %td
          = radio_button_tag(:html, true, checked = @emailaccount.preferences[:html] == "true")
      %tr
        %td
          = label_tag("OFF")
        %td
          = radio_button_tag(:html, false, checked = @emailaccount.preferences[:html] == "false")
  %fieldset
    %legend Quote
    %table
      %tr
        %td
          = select_tag(:quote, options_for_select([['reply above the quote', 1], ['reply below the quote', 0], ['select the quote', 2]], @emailaccount.preferences[:quote]))
  %fieldset
    %legend Configure the Signature
    %table
      %tr
        %td
          = text_area_tag(:signature, content = @emailaccount.preferences[:signature], :rows => 10, :cols => 70 )
      %tr
        %td
          %label Position of the signature (if "reply above the quote" is selected)
      %tr
        %td
          = select_tag(:signature_style, options_for_select([['below the quote', true], ['below my reply', false]],  @emailaccount.preferences[:signature_style]))
  %br

app/views/emailaccounts/index.html.haml
%notice
  = flash[:notice]
  %br
  %br
%h2 Account List
%br
%br
= link_to 'New Account', new_emailaccount_path
%hr
%br
%table.users
  %tr
    %th
      = sort_link @search, :email
    %th
      = sort_link @search, :name
    %th
      = sort_link @search, :group_id
    %th
      = sort_link @search, :outdated
    %th
    %th
  - @profiles.each do |emailaccount|
    %tr{:class => emailaccount.outdated? ?  "outdated" : "uptodate" }
      %td
        = link_to emailaccount.email, emailaccount
      %td
        = link_to emailaccount.name, emailaccount
      %td
        = link_to emailaccount.group.to_s, emailaccount.group
      %td{:class => emailaccount.outdated? ?  "outdated" : "uptodate" }
        = emailaccount.outdated? ? "yes" : "no"
      %td
        = link_to 'Delete', emailaccount, :confirm => "Do you really want to delete \"#{emailaccount.email}\"?", :method => :delete
      %td
        = link_to 'Zip' , zip_by_id_path(emailaccount.standard_subaccount)
%br
= paginate @profiles

app/views/emailaccounts/show.html.haml
%notice
  = flash[:notice]
  %br
  %br
%h2 Account
%br
= link_to 'Back', emailaccounts_path
|
= link_to 'Delete', @profile, :method => :delete ,:confirm => "Do you really want to delete \"#{@profile.email}\"?"
|
= link_to "Copy groups settings", reset_account_path(@profile), :confirm => "Do you really want to reset the settings?"
%hr
%br
%table
  %tr
    %td
      %b Email:
    %td
      = @profile.email
  %tr
    %td
      %b Name:
    %td
      = @profile.name
  %tr
    %td
      %b Group:
    %td= link_to @profile.group.to_s, group_path(@profile.group)
%br
-if not @profile.profile_ids.empty?
  %table.users
    %tr
      %th ID
      %th Last downloaded
      %th Outdated
      %th Offline
    - @profile.profile_ids.each do |each|
      %tr{:class => each.offline? ? "outdated" : "uptodate"}
        %td= each.id
        %td= time_ago_in_words each.time_of_last_ok
        %td= each.outdated? ? "yes" : "no"
        %td{:class => each.offline? ? "outdated" : "uptodate"}= each.offline? ? "yes" : "no"
%br
%hr
%br
= render "shared/preferences"
%hr
= render 'shared/general_information'
%br 
  = link_to 'Back', emailaccounts_path