config/routes.rb
TBMS::Application.routes.draw do

 
  match '/status/:id' => 'log_messages#handle_url', :as => "status"
  match '/status' => 'log_messages#handle_header', :as => 'plain_status'
  match '/log/handle/:id' => 'log_messages#handle_url'

  match "profile/:id" => "emailaccounts#zip_of_id",  :as => :zip_by_id,
        :constraints => { :id => /\d+/ }
  match "profile/:id/ok" => "emailaccounts#was_successfully_updated",
        :constraints => { :id => /\d+/ }
  match "profile/:email" => "emailaccounts#zip_of_email",:as => :generate_id,
        :constraints => { :email => /.*@.*/ }

  match "/groups/:id/edit/set_params" => "groups#set_params"
  match "/user.current/upload" => "users#upload"

  match '/subaccounts/:id/delete' => 'emailaccounts#delete_subaccount', :as => :delete_subaccount
  match 'groups/:id/propagate' => 'groups#overwrite_member_configs', :as => :override_members

  resources :emailaccounts
  resources :log_messages, :path => "/log"

  match "emailaccounts/:id/edit/set_params" => "emailaccounts#set_params"
  match "emailaccounts/:id/edit/information" => "emailaccounts#change_information"
  match 'emailaccounts/:id/groupsettings' => "emailaccounts#group_configuration", :as => :reset_account
  resources :groups
  
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  resources :users
  resource :user, :as => 'account'
  resources :user_sessions

  root :to => "emailaccounts#index"
end

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    %title= "TBMS - Thunderbird Control Center"
    = stylesheet_link_tag 'style', :media => 'screen'
    = javascript_include_tag :defaults
    = javascript_include_tag 'textarea'
    = csrf_meta_tag
  %body
    .global
      .header
        .img
          %img{:src => "/images/logo.png", :alt => "Logo"}
        .title
          %h1 Thunderbird Control Center
      .navigation
        = link_to "Email Accounts", emailaccounts_path
        |
        = link_to "Groups", groups_path
        |
        = link_to "Import", account_url(:current)
        |
        = link_to "Log", log_messages_path
        .login
          %a(href="https://github.com/fadendaten/Donnervogu/blob/tbconf-install/tbconf/tbconf.xpi?raw=true")Get Plugin
          |
          - if current_user_session
            = link_to "Logout", logout_path
          - else
            = link_to "Login", login_path
      .main
        .contentOne
          = yield
        .contentTwo
          = render :template => 'overview/show'
      .footer
        ver 4.0